### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by ianaflous** [coding-war/poker#1]
Salut Kevin, 
J'ai une cette erreur au lancement, tu pourrais me dire pourquoi ?

[nodemon] starting `node -r tsconfig-paths/register -r ts-node/register ./src/index.ts`

C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/poker/game/pokergamefactory.ts(11,20): error TS2554: Expected 0 arguments, but got 1.

    at createTSError (C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\anaflousi\Workspaces\coding war\poker\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by ianaflous** [comment]
C'était bien une incompatibilité entre typescript 2 et 3.
C'est résolu ! Merci
